### ISSUE TITLE
This code gave me 500000 viruses

### ISSUE THREAD

**Issue by SevenworksDev** [HarmOnGitHub/rylix-is-a-skid#1]
delete this virus you ding dong diddly neighorino i will cut off yo arms

**Comment by HarmOnGitHub** [comment]
poor guy

**Comment by SevenworksDev** [comment]
![86219B24-8C3D-42CD-AB3F-71A367071A9A](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/91027492/7118b411-7cbf-4fa2-a1d0-67a8206869f0)

**Comment by cv003** [comment]
![4a3386994aff58fe584e37b5c10cc1e6 png](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/c8783ef7-069b-498e-a0b2-01bb3641ffb6)

**Comment by cv003** [comment]
![image](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/1e07f41d-85d7-4b79-8d39-b7a7eefc8600)

**Comment by cv003** [comment]
![image](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/1e07f41d-85d7-4b79-8d39-b7a7eefc8600)

**Comment by cv003** [comment]
![image](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/1e07f41d-85d7-4b79-8d39-b7a7eefc8600)

**Comment by cv003** [comment]
![image](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/1e07f41d-85d7-4b79-8d39-b7a7eefc8600)

**Comment by cv003** [comment]
![image](https://github.com/HarmOnGitHub/rylix-is-a-skid/assets/86375852/1e07f41d-85d7-4b79-8d39-b7a7eefc8600)
